[extension]
id = "bgql"
name = "Better GraphQL"
description = "Language support for Better GraphQL (.bgql files)"
version = "0.1.0"
schema_version = 1
authors = ["ubugeeei <ubugeeei@example.com>"]
repository = "https://github.com/ubugeeei/bgql"

[language_servers.bgql]
name = "bgql-lsp"
language = "bgql"

[grammars.bgql]
repository = "https://github.com/ubugeeei/bgql"
rev = "main"
